from django.db import models


# Create your models here.
class ShopCategory(models.Model):
    ca_id = models.CharField(max_length=50)
    ca_name = models.CharField(max_length=150)


class ShopItem(models.Model):
    it_id = models.CharField(max_length=20, null=False)
    ca_id = models.CharField(max_length=20, null=True, default='')
    ca_id2 = models.CharField(max_length=20, null=True, default='')
    ca_id3 = models.CharField(max_length=20, null=True, default='')
    it_skin = models.CharField(max_length=20, null=True, default='')
    it_name = models.CharField(max_length=255, default='')
    it_sub_name = models.CharField(max_length=255, default='')
    it_depend_item = models.CharField(max_length=20, default='')
    it_main_item = models.CharField(max_length=20, default='')
    it_co_type = models.CharField(max_length=20, default='')
    it_info = models.TextField(default='')
    it_model = models.CharField(max_length=255, default='')
    it_jisho_status = models.CharField(max_length=25, default='')
    it_type1 = models.BooleanField(default=False)
    it_type2 = models.BooleanField(default=False)
    it_type3 = models.BooleanField(default=False)
    it_type4 = models.BooleanField(default=False)
    it_type5 = models.BooleanField(default=False)
    it_explain = models.TextField(default='')
    it_sub_explain = models.TextField(default='')
    it_cust_price = models.IntegerField(default=0)
    it_price = models.IntegerField(default=0)
    it_use = models.BooleanField(default=False)
    it_quantity = models.IntegerField(default=999)
    it_sc_type = models.CharField(max_length=20, default='')
    it_sc_price = models.IntegerField(default=0)
    it_buy_min_qty = models.IntegerField(default=0)
    it_buy_max_qty = models.IntegerField(default=10)
    it_hit = models.IntegerField(default=0)
    it_time = models.DateTimeField(auto_now_add=True)
    it_update_time = models.DateTimeField(auto_now_add=True)
    it_option_subject = models.CharField(max_length=255, default='')
    it_option = models.TextField(default='')
    it_add_product_subject = models.CharField(max_length=255, default='')
    it_add_product = models.TextField(default='')
    it_use_count = models.IntegerField(default=0)
    it_use_average = models.FloatField(default=0.0)
    it_naver_category = models.CharField(max_length=20, default='')
    it_color = models.CharField(max_length=255, default='')
    it_color_code = models.CharField(max_length=255, default='')
    it_img1 = models.CharField(max_length=150, default='')
    it_img2 = models.CharField(max_length=150, default='')
    it_img3 = models.CharField(max_length=150, default='')
    it_img4 = models.CharField(max_length=150, default='')
    it_img5 = models.CharField(max_length=150, default='')
    it_img6 = models.CharField(max_length=150, default='')
    it_img7 = models.CharField(max_length=150, default='')
    it_img8 = models.CharField(max_length=150, default='')
    it_img9 = models.CharField(max_length=150, default='')
    it_sk_fprice = models.CharField(max_length=100, default='')
    it_sk_capa = models.CharField(max_length=100, default='')
    it_sk_gongsi = models.CharField(max_length=100, default='')
    it_sk_new_dc = models.CharField(max_length=100, default='')
    it_sk_mnp_g_dc = models.CharField(max_length=100, default='')
    it_sk_mnp_s_dc = models.CharField(max_length=100, default='')
    it_sk_gib_g_dc = models.CharField(max_length=100, default='')
    it_sk_gib_s_dc = models.CharField(max_length=100, default='')
    it_kt_fprice = models.CharField(max_length=100, default='')
    it_kt_capa = models.CharField(max_length=100, default='')
    it_kt_gongsi = models.CharField(max_length=100, default='')
    it_kt_new_dc = models.CharField(max_length=100, default='')
    it_kt_mnp_g_dc = models.CharField(max_length=100, default='')
    it_kt_mnp_s_dc = models.CharField(max_length=100, default='')
    it_kt_gib_g_dc = models.CharField(max_length=100, default='')
    it_kt_gib_s_dc = models.CharField(max_length=100, default='')
    it_lg_fprice = models.CharField(max_length=100, default='')
    it_lg_capa = models.CharField(max_length=100, default='')
    it_lg_gongsi = models.CharField(max_length=100, default='')
    it_lg_new_dc = models.CharField(max_length=100, default='')
    it_lg_mnp_g_dc = models.CharField(max_length=100, default='')
    it_lg_mnp_s_dc = models.CharField(max_length=100, default='')
    it_lg_gib_g_dc = models.CharField(max_length=100, default='')
    it_lg_gib_s_dc = models.CharField(max_length=100, default='')