# Generated by Django 4.0.5 on 2022-07-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopconfigapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='it_add_product',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_color',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_color_code',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_hit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_img1',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_img2',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_img3',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_img4',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_img5',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_img6',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_img7',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_img8',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_img9',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_kt_capa',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_kt_fprice',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_kt_gib_g_dc',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_kt_gib_s_dc',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_kt_gongsi',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_kt_mnp_g_dc',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_kt_mnp_s_dc',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_kt_new_dc',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_lg_capa',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_lg_fprice',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_lg_gib_g_dc',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_lg_gib_s_dc',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_lg_gongsi',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_lg_mnp_g_dc',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_lg_mnp_s_dc',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_lg_new_dc',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_naver_category',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_option',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_sk_capa',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_sk_fprice',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_sk_gib_g_dc',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_sk_gib_s_dc',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_sk_gongsi',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_sk_mnp_g_dc',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_sk_mnp_s_dc',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_sk_new_dc',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_use_average',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_use_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
