# Generated by Django 4.0.5 on 2022-07-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopconfigapp', '0002_alter_shopitem_it_add_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='it_buy_max_qty',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_buy_min_qty',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_co_type',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_cust_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_depend_item',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_explain',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_info',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_jisho_status',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_main_item',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_model',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_sc_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_sc_type',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_seq',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_sub_explain',
            field=models.TextField(default='', null=True),
        ),
    ]
