# Generated by Django 4.0.5 on 2022-07-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopconfigapp', '0003_alter_shopitem_it_buy_max_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='it_img1',
            field=models.ImageField(blank=True, null=True, upload_to='item_img/'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_img2',
            field=models.ImageField(blank=True, null=True, upload_to='item_img/'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_img3',
            field=models.ImageField(blank=True, null=True, upload_to='item_img/'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_img4',
            field=models.ImageField(blank=True, null=True, upload_to='item_img/'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_img5',
            field=models.ImageField(blank=True, null=True, upload_to='item_img/'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_img6',
            field=models.ImageField(blank=True, null=True, upload_to='item_img/'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_img7',
            field=models.ImageField(blank=True, null=True, upload_to='item_img/'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_img8',
            field=models.ImageField(blank=True, null=True, upload_to='item_img/'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='it_img9',
            field=models.ImageField(blank=True, null=True, upload_to='item_img/'),
        ),
    ]
