# Generated by Django 4.0.5 on 2022-07-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopconfigapp', '0004_alter_shopitem_it_img1_alter_shopitem_it_img2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='it_main_item',
            field=models.BooleanField(default=False),
        ),
    ]
